language: cpp
dist: xenial
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - libglfw3-dev
      - libglm-dev

before_install:
  - chmod +x ./thirdparty/travis_discord_hook.sh
  - ./thirdparty/travis_discord_hook.sh started $WEBHOOK_URL

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake .
  - make

after_success:
  - ./thirdparty/travis_discord_hook.sh success $WEBHOOK_URL

after_failure:
  - ./thirdparty/travis_discord_hook.sh failure $WEBHOOK_URL
